// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YourNamespace.Data;

#nullable disable

namespace HUMIO_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250201153814_Migration2")]
    partial class Migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HUMIO_API.Model.DeviceIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DeviceIdentifiers");
                });

            modelBuilder.Entity("HUMIO_API.Model.Premium", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CurrentPurchaseCost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("SubscriptionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("Premiums");
                });

            modelBuilder.Entity("HUMIO_API.Model.Trial", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TrialEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("Trials");
                });

            modelBuilder.Entity("HUMIO_API.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HUMIO_API.Model.UserStats", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchaseCount")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TimeSpentInApp")
                        .HasColumnType("interval");

                    b.Property<decimal>("TotalPurchaseAmount")
                        .HasColumnType("numeric");

                    b.HasKey("UserId");

                    b.ToTable("UserStats");
                });

            modelBuilder.Entity("HUMIO_API.Model.DeviceIdentifier", b =>
                {
                    b.HasOne("HUMIO_API.Model.User", "User")
                        .WithMany("DeviceIdentifiers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HUMIO_API.Model.Premium", b =>
                {
                    b.HasOne("HUMIO_API.Model.User", "User")
                        .WithOne("Premium")
                        .HasForeignKey("HUMIO_API.Model.Premium", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HUMIO_API.Model.Trial", b =>
                {
                    b.HasOne("HUMIO_API.Model.User", "User")
                        .WithOne("Trial")
                        .HasForeignKey("HUMIO_API.Model.Trial", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HUMIO_API.Model.UserStats", b =>
                {
                    b.HasOne("HUMIO_API.Model.User", "User")
                        .WithOne("UserStats")
                        .HasForeignKey("HUMIO_API.Model.UserStats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HUMIO_API.Model.User", b =>
                {
                    b.Navigation("DeviceIdentifiers");

                    b.Navigation("Premium")
                        .IsRequired();

                    b.Navigation("Trial")
                        .IsRequired();

                    b.Navigation("UserStats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
